defaults:
  - _self_
  - model: distilbert

seed: 1776

data:
  format: "json"
  train_path: "/root/data/msmarco_triplets/msmarco-triplets.jsonl.gz"

batch_size: 8
num_negatives: 4
lambda_d: 5e-4
lambda_q: 5e-4
T_d: 10000
T_q: 10000
top_k_doc: 256
top_k_query: 64
epochs: 10

optimizer:
  learning_rate: 3e-5
  warmup_steps: 1000
  every_k_schedule: 4

checkpoint:
  max_to_keep: 3
  save_interval_steps: 5000
  checkpoint_path: "checkpoints/test4"
wandb: True
wandb_project: "splade-distilbert"
log_every: 20
